default:
    # Misc. routes
    'GET /health-check': 'DefaultController#health_check'

    # Users API
    'POST /user/login': 'UserController#login'
    'POST /user/register': 'UserController#register'
    'GET /user/session': 'UserController#session'
    'GET /user/logout': 'UserController#logout'

    # Blueprint API
    'GET /:extension/:name/definition': 'ItemsController#definition'
    'GET /items': 'ItemsController#find_all'
    'GET /items/:id': 'ItemsController#find'
    'PUT /items/:id': 'ItemsController#update'
    'POST /items': 'ItemsController#create'
    'DELETE /items/:id': 'ItemsController#delete'

    # Extensions API
    'GET /extensions': 'ExtensionsController#find_all'

    # Blueprints API
    'GET /blueprints': 'BlueprintsController#find_all'
