default:
    # Misc. routes
    'GET /health-check': 'DefaultController#health_check'

    # User API
    'POST /user/login': 'UserController#login'
    'POST /user/register': 'UserController#register'
    'GET /user/session': 'UserController#session'
    'GET /user/logout': 'UserController#logout'

    # Users API
    'GET /users': 'UsersController#find_all'
    'GET /users/:id': 'UsersController#find'
    'PUT /users/:id': 'UsersController#update'
    'POST /users': 'UsersController#create'
    'DELETE /users/:id': 'UsersController#delete'

    # Groups API
    'GET /groups': 'GroupsController#find_all'
    'GET /groups/:id': 'GroupsController#find'
    'PUT /groups/:id': 'GroupsController#update'
    'POST /groups': 'GroupsController#create'
    'DELETE /groups/:id': 'GroupsController#delete'

    # Blueprint API
    'GET /:extension/:name/definition': 'ItemsController#definition'
    'GET /items': 'ItemsController#find_all'
    'GET /items/:id': 'ItemsController#find'
    'PUT /items/:id': 'ItemsController#update'
    'POST /items': 'ItemsController#create'
    'DELETE /items/:id': 'ItemsController#delete'

    # History API
    'GET /histories': 'HistoryController#find_all'
    'GET /histories/:id': 'HistoryController#find'
    'PUT /histories/:id': 'HistoryController#update'
    'POST /histories': 'HistoryController#create'
    'DELETE /histories/:id': 'HistoryController#delete'

    # Extensions API
    'GET /extensions': 'ExtensionsController#find_all'

    # Blueprints API
    'GET /blueprints': 'BlueprintsController#find_all'
