default:
    # Misc. routes
    'GET /health-check': 'DefaultController#health_check'

    # User API
    'POST /user/login': 'UserController#login'
    'POST /user/register': 'UserController#register'
    'GET /user/session': 'UserController#session'
    'GET /user/logout': 'UserController#logout'

    # Users API
    'GET /users': 'UsersController#find_all'
    'GET /users/:id': 'UsersController#find'
    'PUT /users/:id': 'UsersController#update'
    'POST /users': 'UsersController#create'
    'DELETE /users/:id': 'UsersController#delete'

    # Groups API
    'GET /groups': 'GroupsController#find_all'
    'GET /groups/:id': 'GroupsController#find'
    'PUT /groups/:id': 'GroupsController#update'
    'POST /groups': 'GroupsController#create'
    'DELETE /groups/:id': 'GroupsController#delete'

    # Permissions API
    'GET /permissions': 'PermissionsController#find_all'
    'GET /permissions/:id': 'PermissionsController#find'
    'PUT /permissions/:id': 'PermissionsController#update'
    'POST /permissions': 'PermissionsController#create'
    'DELETE /permissions/:id': 'PermissionsController#delete'

    # Files API
    'GET /files': 'FilesController#find_all'
    'GET /files/:id': 'FilesController#find'
    'POST /files': 'FilesController#create'
    'DELETE /files/:id': 'FilesController#delete'

    'GET /files/show/:id': 'FilesController#show'
    'GET /files/download/:id': 'FilesController#download'

    # Image routes
    'GET /image/width/:width/:id.:format': 'ImageController#show'
    'GET /image/height/:height/:id.:format': 'ImageController#show'
    'GET /image/:width/:height/:id.:format': 'ImageController#show'
    'GET /image/scale/:scale/:id.:format': 'ImageController#show'
    'GET /image/:width/:height/:crop_origin_x/:crop_origin_y/:id.:format': 'ImageController#show'
    'GET /image/:scale/:width/:height/:crop_origin_x/:crop_origin_y/:id.:format': 'ImageController#show'

    # Blueprint API
    'GET /:extension/:name/definition': 'ItemsController#definition'
    'GET /items': 'ItemsController#find_all'
    'GET /items/:id': 'ItemsController#find'
    'PUT /items/:id': 'ItemsController#update'
    'POST /items': 'ItemsController#create'
    'DELETE /items/:id': 'ItemsController#delete'

    # History API
    'GET /histories': 'HistoriesController#find_all'
    'GET /histories/:id': 'HistoriesController#find'
    'PUT /histories/:id': 'HistoriesController#update'
    'POST /histories': 'HistoriesController#create'
    'DELETE /histories/:id': 'HistoriesController#delete'

    # Extensions API
    'GET /extensions': 'ExtensionsController#find_all'
    'GET /extensions/:id': 'ExtensionsController#find'

    # Blueprints API
    'GET /blueprints': 'BlueprintsController#find_all'
    'GET /blueprints/:id': 'BlueprintsController#find'

    # Blueprint Item API
    'GET /:extension/:blueprint_slug': 'ItemsController#find_all'
    'GET /:extension/:blueprint_slug/:id': 'ItemsController#find'
    'PUT /:extension/:blueprint_slug/:id': 'ItemsController#update'
    'POST /:extension/:blueprint_slug': 'ItemsController#create'
    'DELETE /:extension/:blueprint_slug/:id': 'ItemsController#delete'
