default:
  port: 5000
  secret_key: "O8]qD&>~#R15=Q]1!c56{30r92-6[63$(C~{{PJ"

  controller_directory: '../controllers'

  cors_enabled: true
  cors_origin: 'http://localhost:4200'

  file_storage: Local

  search_adapter: 'SearchIndex'
  search_index_path: './data/index'

test:
  port: 5001

  file_storage: Mock
