default:
  port: 5000
  secret_key: "O8]qD&>~#R15=Q]1!c56{30r92-6[63$(C~{{PJ"

  controller_directory: '../controllers'

  cors_enabled: true
  cors_origin: 'http://localhost:4200'

test:
  port: 5001
