name:
  type: 'text'
  options:
    show_in_list: true
style:
  type: 'text'
  options:
    show_in_list: true
brand:
  belongs_to: 'Brand'
category:
  belongs_to: 'Category'
department:
  type: 'text'
class:
  type: 'text'
  options:
    show_in_list: true
price:
  type: 'text'
  options:
    show_in_list: true
description:
  type: 'richtext'
